version: '3.8'

services:
  bolhadev-chat:
    build:
      dockerfile: ./docker/apps/Dockerfile
      args:
        PROJECT: server
    image: brunoroh/bolhadev-chat:latest

  nginx:
    build: ./docker/nginx/
    image: brunoroh/bolhadev-nginx:latest
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - bolhadev-chat
